### ISSUE TITLE
Syntax Error while installing on SAP ABAP Platform Developer Edition

### ISSUE THREAD

**Issue by nomssi** [SAP/abap-file-formats-tools#108]
Syntax Error: Line 8 in Program Z_GENERATE_REPO - Type "SAFF_REPO_TYPES" is unknown.
Warning: Line 75 in Program Z_GENERATE_JSON_SCHEMA - Unknown pragma "REGEX_POSIX".
![image](https://user-images.githubusercontent.com/18452507/169609498-2dc58f2d-a1e3-4412-a225-a7073c2dcdb0.png)
JNN

**Comment by larshp** [comment]
hi,
The reports as such, are just temporary.

on long term, the logic will hopefully run standalone on github actions

personally I've not tried installing on dev edition yet, as I expected it to fail 😄

**Comment by albertmink** [comment]
Hi @nomssi,

be aware that report `Z_GENERATE_REPO` is for internal development - so you might ignore the errors.

There has been some work to change the Regex to posix, see #5. It seams that there are some left overs. Feel free to open a pull request.

**Comment by larshp** [comment]
status, 

* CL_OO_ABAP_DOC_READER is being moved to ZCL_OO_ABAP_DOC_READER
* error in Z_GENERATE_REPO is okay, its just temporary, and/or part of core logic

![image](https://user-images.githubusercontent.com/5888506/173867024-cb89c010-c534-44da-b8ec-bcaca2f5fd97.png)

**Comment by larshp** [comment]
@nomssi try again

Z_GENERATE_REPO still have errors, but its not central logic, and when I'm done it does not need to be used

**Comment by larshp** [comment]
closing
