### ISSUE TITLE
cl_oo_abap_doc_reader, reading source code of class/intf

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats-tools#160]
`zcl_aff_abap_doc_reader` takes the source as input in `create_instance`

`cl_oo_abap_doc_reader` takes the name of the class/interface as input

to glue it together, we should read the source code, but which method is preferred to read class and intf source code? `CL_OO_CLIF_SOURCE` ?

**Comment by larshp** [comment]
ok, so something like this?

```abap
DATA(ref) = cl_oo_factory=>create_instance( )->create_clif_source( 'CL_GUI_FRONTEND_SERVICES' ).
ref->get_source( IMPORTING source = DATA(sovs) ).
BREAK-POINT.
```

**Comment by schneidermic0** [comment]
Yes, this is fine... except the `BREAK-POINT` statement :D
