### ISSUE TITLE
MaxLength is currently limited to 255

### ISSUE THREAD

**Issue by huber-nicolas** [SAP/abap-file-formats-tools#190]
Currently the max maxLength in the generated json schemas is 255 due to a bug.
For example if the abap type has a field "name type c length 512" the schema generator will put "maxLength":255 into the schema.

I am working on this problem

**Comment by schneidermic0** [comment]
It's a bug in the tooling. Therefore, I have just transfered it to https://github.com/sap/abap-file-formats-tools

**Comment by schneidermic0** [comment]
Output length in RTTI is limited to max. 255 characters. Therefore, the implementation needs to be changed as in #189

**Comment by huber-nicolas** [comment]
fixed by #189
