### ISSUE TITLE
SMBC, missing update or bug?

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats-tools#195]
SMBC was updated with https://github.com/SAP/abap-file-formats/pull/416/files

looking at the code https://github.com/SAP/abap-file-formats-tools/blob/d3ba437c12f34b3bc630151774776a77e8690b64/src/zcl_aff_writer_json_schema.clas.abap#L336-L341

then whenever the json contains "enumTitles" it will also have "enumDescriptions"

however, this is not the case for https://github.com/SAP/abap-file-formats/blob/main/file-formats/smbc/smbc-v1.json#L147 ?

something looks wrong...

**Comment by schneidermic0** [comment]
We just discussed this. We think the descriptions can be optional (same as we did it for the titles here):

https://github.com/SAP/abap-file-formats-tools/blob/d3ba437c12f34b3bc630151774776a77e8690b64/src/zcl_aff_writer_json_schema.clas.abap#L335-L338

**Comment by schneidermic0** [comment]
You are right. It seems it was changed manually afterwards. 
We would have to ask whether this was removed manually or whether some magic happened which we have not understood, yet ;)

**Comment by larshp** [comment]
yea, makes sense

tho, originally I was only after finding out if the generated file contained whatever is generated

**Comment by larshp** [comment]
any progress on this issue? I'd just update the generated schema in git so it matches the generated json schema
