### ISSUE TITLE
Readme fix link to example

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats-tools#299]
Did you generate the output of the readme file using our program? 
If so, there seems to be an issue with the generator for the readme file.

```suggestion
`<name>.sajt.json` | 1 | [`zif_aff_sajt_v1.intf.abap`](./type/zif_aff_sajt_v1.intf.abap) | [`sajt-v1.json`](./sajt-v1.json) | [`z_aff_example_sajt.sajt.json](./examples/z_aff_example_sajt.sajt.json)
```

_Originally posted by @schneidermic0 in https://github.com/SAP/abap-file-formats/pull/578#discussion_r1430165551_

**Comment by albertmink** [comment]
duplicate of #300

**Comment by schneidermic0** [comment]
Sorry, I missed your issue.
