### ISSUE TITLE
Artefacts not available here

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats-tools#3]
There are some left overs from the Abap development system, that are not contained in this repository.
Many won't make it into the repository and hence should be removed.

The list
- [x] #21
- [x] #18
- [x] #20
- [ ] `cl_oo_abap_doc_reader`
- [x] #36
- [ ] https://github.com/SAP/abap-file-formats-tools/blob/main/src/zcl_aff_writer_json_schema.clas.abap#L990'
- [x] #37
- [ ] #45 
- [x] to be continued

**Comment by larshp** [comment]
I think `cl_oo_abap_doc_reader` is the only left? close this issue and open a separate for tracking `cl_oo_abap_doc_reader` ?

**Comment by albertmink** [comment]
the leftovers are covered in the new issue.
