### ISSUE TITLE
Remove reference to `if_sxml_writer` or provide this interface

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats-tools#37]

**Comment by albertmink** [comment]
Here https://github.com/SAP/abap-file-formats-tools/blob/main/src/zcl_aff_writer_xstl.clas.testclas.abap#L970' #37
and in its test classes

**Comment by larshp** [comment]
it is released, https://abapedia.org/steampunk-2202-api/if_sxml_writer.intf.html

so it can be added to [open-abap](https://github.com/open-abap/open-abap)

**Comment by albertmink** [comment]
good information 👉 close the issue here
