### ISSUE TITLE
PCRE regexes is 755, latest dev edition is 754

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats-tools#5]
PCRE regexes is 755, latest dev edition is 754

need to decide the target version of this repository, I'd suggest it follows the [latest dev edition](https://hub.docker.com/_/sap-abap-trial)

tho it might be difficult, PCRE is a good feature

**Comment by wurzka** [comment]
Most occurrences of PCRE can be easily replaced. 

Problems are caused only by this place:
https://github.com/SAP/abap-file-formats-tools/blob/bb2a5b44c3c09d7463a70a2558c0956cc6d21d0c/src/zcl_aff_abap_doc_parser.clas.abap#L121

With PCRE you can enable greedy search by adding `?`, REGEX only allows lazy search.
If `?` was removed, the occurrence of multiple shorttexes would lead to a strange title.

**Comment by larshp** [comment]
suggest this workaround, perhaps split it into a method,

1: find all `<p\sclass="shorttext">`
2: for each of the findings, split at "</p>
3: first entry in the split is each a result for `result_table`
