### ISSUE TITLE
The npm magic 🌹 

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats-tools#74]
This works
```
npm run lint
```
This does not
```
npm run test
```
![image](https://user-images.githubusercontent.com/38354196/164454494-58d7755b-a97b-45ab-8713-1c5832c485d0.png)

I deleted the `node_modules` folder and cleaned the npm cache. Still, it does not work.
Suggestions welcome 👋

**Comment by larshp** [comment]
are you on mac/windows/linux/other?

try using Bash

`rm` and `cp` doesnt work well on all platforms

**Comment by albertmink** [comment]
It is the famous
![image](https://user-images.githubusercontent.com/38354196/164458945-151b218e-bcb5-44e1-bfd4-9293d4752626.png)
Typically this terminal does the job and is a fairly good approximation of a Linux bash

**Comment by albertmink** [comment]
Same here for another Windows bash
<img width="187" alt="image" src="https://user-images.githubusercontent.com/38354196/164462498-d033757a-c5cb-438a-9e0c-11b973bd116a.png">

**Comment by larshp** [comment]
okay, I think it works as expected, its just difficult to tell from the first screenshot

test contains 3 steps,
`"test": "npm run lint && npm run downport && npm run unit",`

the step "npm run downport" fails with exit code 1, ie. it does not run "npm run unit"

for now, do "npm run downport", which will return an exit code, but not something that you will notice

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/164464414-c1db34ba-f178-4e73-9b52-94eeaa0f5911.png)

**Comment by albertmink** [comment]
Depending on the environment, the exit status of the Abaplint is interpreted differently. In both situations there are 33 issues and the very last output is `Fixes applied`.

**Comment by albertmink** [comment]
By the way, the result is the same for `npm run downport` and `npm run test`.

**Comment by larshp** [comment]
@albertmink did you get this working?
