### ISSUE TITLE
enable rule line_only_punc?

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats-tools#79]
Any thoughts on enabling https://rules.abaplint.org/line_only_punc/ ?

there are 170 occurrences which can be quick fixed, https://abaplint.app/stats/SAP/abap-file-formats-tools/disabled_rules

its part of the style guide, https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#close-brackets-at-line-end

**Comment by albertmink** [comment]
Enable 😃
